### ISSUE TITLE
Buttons are not working properly.

### ISSUE THREAD

**Issue by harshitagupta30** [systers/powerup-android#294]
On clicking the replay button, nothing happens while on clicking the continue the quiz again starts.
Instead of this on clicking the replay the quiz should start again.

![videotogif_2017 01 29_20 17 03](https://cloud.githubusercontent.com/assets/12701036/22404905/40e372b2-e660-11e6-8766-f42c57ed6a40.gif)

@anubhakushwaha @chhavip Can I work on this issue?

**Comment by aanchal07** [comment]
@harshitagupta30 On clicking the continue button, the next conversation appears which might be same as the previous one. You don't need to change the functionality of continue button but you can send a PR adding the replay button functionality. Before sending the PR please specify what you intend to do so that we can approve that.

**Comment by anubhakushwaha** [comment]
@chhavip @aanchal07 The work for replay has already been implemented nicely during gci via #186 ,do we need anyother thing other than the work already done in the PR mentioned.

**Comment by aanchal07** [comment]
I think if the work has already been done we can just merge that PR.

**Comment by aanchal07** [comment]
I think if the work has already been done we can just merge that PR.

**Comment by chhavip** [comment]
Merging the existing PR and closing this issue.
