### ISSUE TITLE
Game ends for each scenario if one scenario is finished

### ISSUE THREAD

**Issue by codeb1ooded** [systers/powerup-android#315]
Though questions are same for all scenarios (which might change in future) even then I guess if one scenario is over others should not be over.

Fix I suggest:
Each scenario keeps track of only its status and not all scenarios have a single status for ScenarioOverActivity.

@anubhakushwaha @chhavip Can I work on this issue?

**Comment by anubhakushwaha** [comment]
@codeb1ooded Could you please elaborate? Further see if #174 is related to what you suggest and carry the discussion there instead.

**Comment by BaaniLeen** [comment]
![video](https://cloud.githubusercontent.com/assets/22029744/24078665/c3b43fbe-0c99-11e7-9e64-71ca5a164b17.gif)

On starting the game as a new user and clicking on the Hospital scene,on completing the Hospital Scene, it shows 'completed_game.xml', instead of showing 'completed_scene.xml'.
Only when all the 4 scenes are over should it show completed_game.xml'.

@chhavip @aanchal07 Can I work on this?
Thanks!

**Comment by BaaniLeen** [comment]
@aanchal07 Can I please work on this? :)

**Comment by mahikaw** [comment]
@BaaniLeen this is a duplicate issue to #241 
@codeb1ooded it is advised to go through the existing list of issues before opening a new one. :)
