### ISSUE TITLE
Enhancement: Add theme Chooser on app start up.

### ISSUE THREAD

**Issue by top-gun007** [systers/powerup-android#365]
**Summary**
Since the app is centred around age group 12-18. I suggest we add a list of science fiction women character(eg Wonder Women, Super Girl, Black Widow etc) and on selecting on any one of the theme(Mainly the colour of the buttons at the home screen) of the app changes:
**Something Like this**  
![image](https://cloud.githubusercontent.com/assets/15179401/24668519/ceb939d0-1984-11e7-8b8a-3ecdb075fc22.png)

**Comment by asclepiusgal** [comment]
Cool idea! Unfortunately I don't think you'll be able to publish the app on
the Google Play store without getting hit with the automatic copyright
infringement due to using proprietary Marvel stuff. Also, comic book color
themes may not be targeting the right demographic; saying this since I
personally wouldn't have 'loved' that feature as a primary school girl and
I was more of a tomboy than most of my female friends.

**Comment by top-gun007** [comment]
@asclepiusgal I am not saying about using the logos which are a copywriter materiel but instead of that we can use their names and show using a list of some sort of.

**Comment by aanchal07** [comment]
I don't think we can include this feature as of now.
