### ISSUE TITLE
Edit the footer

### ISSUE THREAD

**Issue by aanchal07** [systers/powerup-android#366]
Remove the telepathy and invisibility powers from the power bar. Also remove the current emotion.

**Comment by top-gun007** [comment]
@aanchal07 I would like to work on it!

**Comment by aanchal07** [comment]
@top-gun007 How are you planning to implement it?

**Comment by top-gun007** [comment]
I plan to approach it in the following manner:

- Remove invisibility and telepathy power from game_activity.xml and then in align healing and strength powers horizontally.

- Redesign power_status_bar.png in order to remove Current emotion using Photoshop.

- Remove the corresponding db entries/functions of invisibility and telepathy powers in the following: PowerUpContract.java/DataHandler.java/AbstractDbAdapter.java/Score.java

**Can I proceed with this approach @aanchal07 ?**
Thank you

**Comment by aanchal07** [comment]
Since we will be doing some redesigning during this gsoc, closing this issue.
