### ISSUE TITLE
Developer needs UI elements for the minesweeper game.

### ISSUE THREAD

**Issue by MeepyMay** [systers/powerup-android#400]
## Description
As a developer,
I want to code the minesweeper game,
so that I can code it into the sex scenario.

## Mocks
![screen shot 2017-06-10 at 20 37 50](https://user-images.githubusercontent.com/2440938/27007308-b6b833c8-4e1c-11e7-8031-03201fe71230.png)

## Acceptance Criteria
- Red, Green, and White Dots all consistent.
- Winning Screen
- Losing Screen

## Definition of Done
- Passes user testing per acceptance criteria items.
- Featured in design meeting.
- Approved by UI team. (Dil & May)

## Estimation
5 Hours

**Comment by codingblazer** [comment]
@MeepyMay @kimhwins Have we finalized about the mode of the game - landscape or portrait.

**Comment by kimhwins** [comment]
@codingblazer  not sure if we ever finalized it, but I designed it in landscape! let me know what you think, the stars are yellow instead of white to keep with our color palette, and would turn red/green accordingly

![minesweeper](https://user-images.githubusercontent.com/22511190/27008422-87db64cc-4e3e-11e7-8b8c-58c97381fb28.png)

**Comment by codingblazer** [comment]
@kimhwins Yes, even I wanted it to be in landscape. Looks really great !! :-)

**Comment by MeepyMay** [comment]
@codingblazer @kimhwins We finalized it in landscape mode. :)

**Comment by kimhwins** [comment]
@codingblazer  it would be really cool to have a card flip animation when the player taps on a star!

**Comment by codingblazer** [comment]
@kimhwins Great idea !! I will sure do that
