### ISSUE TITLE
Scene Completed after conversation irrespective of completion of mini-game

### ISSUE THREAD

**Issue by codeb1ooded** [systers/powerup-android#499]
As seen in GIF, if in some scenario user backs and opens the scenario again after completing the conversation, the scenario is marked completed on revisiting it. It doesn't matter if the user has played the mini-game of scenario. Can I work on this issue?

![1wu6qn](https://user-images.githubusercontent.com/16864336/31052766-76362ab6-a6ab-11e7-8271-0f03ccab5a7f.gif)

**Comment by medhach** [comment]
I'm going to try to solve this one.
-Tia Zhang

**Comment by medhach** [comment]
I didn't manage to solve this, but I think the problem is that "Returns home" is considered a valid answer and is sometimes the last answer in the dialogue. If I'm correct, the scenario is marked "Complete" as soon as you as soon as you finish the dialogue, and since "Returns home" is a valid answer, then the scenario is considered complete before you even enter the mini game. I tried to make it exit the dialogue whenever you pick "returns home," before it could be marked complete, but that caused other problems. 
This was my if statement, so no one else tries to do this: 
          if(position % 15 == 0 && position <= 45 && position > 0) { //This should avoid completion if you choose "returns home"
I suggest either moving completion to the end of a mini game (maybe detect whether or not a mini game is after the dialogue) or trying to exit the dialogue like me but don't screw it up.
Also, there's a method named getAvatarNeckalce instead of getAvatarNecklace. I fixed it in my version, but since I didn't fix the bug, I'm not committing mine. 

-Tia Zhang

**Comment by codingblazer** [comment]
@medhach This issue definitely needs to be addressed. The answer to this problem lies in updateScenario() function of GameActivity.java. 

In CSV files, the type (-1, -2, -3) are used to indicate the end of any mini-game conversations. The scenario is set completed after this. I think the behavior should be to mark conversations end as a checkpoint.

I implemented the same behavior for Minesweeper Game. You can do a similar thing with other mini-games.

**Comment by erikaaatan** [comment]
I would like to claim this issue for the GCI task

**Comment by ZoroarkDarkrai** [comment]
I would like to claim this issue if it's not been resolved yet.

**Comment by luo-yuyuan** [comment]
I would like to work on this. :)

**Comment by MKDEVELOPEMENT** [comment]
i would like to work on this, have claimed it on gci
