### ISSUE TITLE
Avatar needs more inclusive features.

### ISSUE THREAD

**Issue by MeepyMay** [systers/powerup-android#522]
## Description
As a user,
I want to create an avatar that reflects who I am,
so that I can connect with the avatar.

## Mocks
Use for reference on inclusive designs. 
[Systers Open Source Slack Icons](https://www.dropbox.com/sh/2cesickgzx6c35h/AADddkIMQ2T_cXgytYkY9zg1a?dl=0)

### Religions [Required]
Muslim: 
• Hijab (showing some hair, more colors)
• al-Amira (showing no hair, more colors)

### Eyes Color [Required]
Dark Brown

### Accessories [Required]
Hair: 
• Clips
• Hair Band
Face: 
• Glasses
• Surgical Masks ([Visual Kei Masks](https://www.google.com.lb/search?q=visual+kei+masks&source=lnms&tbm=isch&sa=X&ved=0ahUKEwj93siZkcvVAhVCOBQKHdE6BDsQ_AUICigB&biw=1440&bih=826), [Cute Japanese Masks](https://www.google.com.lb/search?biw=1440&bih=826&tbm=isch&sa=1&q=japanese+cute+face+masks&oq=japanese+cute+face+masks&gs_l=psy-ab.3...9415.10019.0.10242.5.5.0.0.0.0.0.0..0.0....0...1.1.64.psy-ab..5.0.0.7RZA0-gGm_E))
Neck:
• Headphones

### Clothes [Required]
Tops: 
• T-Shirt
• Blouse
• Hoodies/Sweatshirts
Bottoms:
• Pants
• Shorts
• Skirts
Full Body:
• Dresses
• Rompers
Shoes:
• Flats
• Sneakers

### Accessibility
• Wheelchair (only the wheelchair, altering the avatar to sitting position will be a stretch goal)
• Crutches 

## Definition of Done
- At least 4 items created.
- Approved by UI team. (Kim & May)

## Estimation
20 hours

**Comment by debanjanah** [comment]
@MeepyMay @kimhwins I am working on the wheelchair. Since the current avatar doesn't have feet, it would be inconsistent to draw the wheelchair and then later add the avatar in sitting position where the avatar has feet. For immediate use, I started by leaving the lower portion out of the avatar. But I'm not sure if the wheelchair must look this way, since everything's 2D in the app. Should I continue doing it this way or should there be changes?
![wheelchair avatar](https://user-images.githubusercontent.com/11819085/31799182-3a5efeb4-b556-11e7-8f07-a1807415574f.png)

**Comment by MeepyMay** [comment]
Hey @debanjanah! 

Let me check in with a couple of resources who know about inclusivity and accessibility.

**Comment by sunakshi96** [comment]
@MeepyMay 
I am working on this issue and have tried making four avatars. I am attaching them here, kindly review
Thank you.
![picture-4](https://user-images.githubusercontent.com/9900938/31860085-a10897a0-b732-11e7-80ea-e6153148b95a.png)
![picture-3](https://user-images.githubusercontent.com/9900938/31860086-a13b839a-b732-11e7-8a3a-16797bcd214a.png)
![picture-2](https://user-images.githubusercontent.com/9900938/31860087-a16c43fe-b732-11e7-94ac-a3c9dec582e9.png)
![picture-1](https://user-images.githubusercontent.com/9900938/31860088-a19d893c-b732-11e7-9a97-ffc0aa1b20ac.png)

**Comment by MeepyMay** [comment]
@sunakshi96 Have you built the app? These avatars cannot be used in the game. It's not the correct format. 

Here's the [version2.0 artwork](https://github.com/systers/powerup-android/tree/design/UI). Please take a look at the current work.

**Comment by sunakshi96** [comment]
@MeepyMay Thank you for reviewing the work and I went through the designs at the version2.0 artwork. I understood that we need to work on the individual elements  rather than composing it whole. Another fact I noticed is the issue was tagged hacktoberfest 2 days ago and it is removed today. I am confused why it is so?(since october is not over yet :) )

**Comment by debanjanah** [comment]
@meepymay Is there any update on the wheelchair design?

**Comment by anumehaagrawal** [comment]
Can I work on this issue as well ?

**Comment by MeepyMay** [comment]
@sunakshi96 The styles should match as much as possible. For example, you matched the version 1.0 design very well in this [PR #526](https://github.com/systers/powerup-android/pull/526/files).

Systers hasn't participated in Hacktoberfest. I only added the label to test and check what's required for Hacktoberfest (from an org perspective), but currently, we don't have a CONTRIBUTING.md to participate. 

@debanjanah @sunakshi96 @anumehaagrawal, I'm closing this issue and adding new ones! :)
