### ISSUE TITLE
UI bug: glitchy text wrapping in scenario

### ISSUE THREAD

**Issue by debanjanah** [systers/powerup-android#528]
I am not very sure if this is a valid issue because considering the GUI mocks from the scenario folder, a lot of code might not have been merged with the current version we were required to build to test the app.
Here is a screenshot from the app emulated in a Nexus 5 API 23 (x86) mobile device where glitchy text wrapping takes place.
This doesn't make the selection of given choices easy as users need to scroll down inside the callout.
![issue](https://user-images.githubusercontent.com/11819085/31957012-e2de8f48-b90a-11e7-8586-84558cbb14d5.JPG)
Also, there was a home icon on the top right corner, but on returning to the previous screen and then coming back to this scenario again, the home button disappears.

**Comment by Rimjhim28** [comment]
@debanjanah As far as the disappearance of home button is concerned, it seems to be an implementation rather than an issue. Going through the codebase I found this:

 if (scene.getReplayed() == 1) {
            goToMap.setAlpha((float) 0.0);
        }
(goToMap is the view id for the home button)

It seems that if a scenario is replayed, the home button "disappears" intentionally. Though, @MeepyMay  @codingblazer would be better people to answer this.

**Comment by MeepyMay** [comment]
#768 addresses this as well. Closing for now.
