### ISSUE TITLE
Reduce code size

### ISSUE THREAD

**Issue by anumehaagrawal** [systers/powerup-android#539]
A lot of activities have redundant and repeatitive lines of code which make debugging hard.
Can i work on this issue ?

**Comment by codingblazer** [comment]
@anumehaagrawal Can you list the activities with a small description (about what is the redundant part in that activity). Also, there is some unnecessary code in some activities which is to be removed.

**Comment by anumehaagrawal** [comment]
@codingblazer  In almost all the activities there are a lot of Image view declarations and methods which do the same thing but with different name . So all of them can be looped in a for loop and reduce code size. For eg . In DressingRoom Activity :-
-
String eyeImageName = getResources().getString(R.string.eye);
        eyeImageName = eyeImageName + getmDbHandler().getAvatarEye();
        ourRID = new R.drawable();
        try {
            photoNameField = ourRID.getClass().getField(eyeImageName);
            eyeView.setImageResource(photoNameField.getInt(ourRID));
        } catch (NoSuchFieldException | IllegalAccessException
                | IllegalArgumentException error) {
            error.printStackTrace();
        }

This piece of code has been repeated for hair, face,necklace etc and can just be put in a function where parameters like face, eye are passed through a loop.
This would make the code look clean and easily readable

**Comment by anumehaagrawal** [comment]
@codingblazer  can i work on it?

**Comment by codingblazer** [comment]
Hi, @anumehaagrawal. The issue is certainly valid and can be worked on. 
But please describe the issue completely for others. The issue needs to be updated with **specific** names of activities that have this redundant code like I told earlier. This prevents other contributors from creating similar issues and understanding which files you will work on. 
Also, please follow [this](https://github.com/systers/powerup-android/issues/465) issue template in future.
Let's discuss the approach once you have updated the issue. I think we can address this using OOPs design patterns (which project currently lacks).

**Comment by anumehaagrawal** [comment]
@codingblazer  is this fine?

**Comment by anumehaagrawal** [comment]
@codingblazer  Can i proceed with this ?

**Comment by MeepyMay** [comment]
@anumehaagrawal  This was addressed earlier in #514. Create a new issue following the new issue template and document the work you want to do.
